# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""Demo for AlphaTensor-Quantum.

This demo showcases how to connect the components of AlphaTensor-Quantum with an
existing third-party library, MCTX (https://github.com/google-deepmind/mctx).
MCTX is a package for training and evaluating AlphaZero agents on a variety of
games.

Inspired by the MCTX demo at https://github.com/kenjyoung/mctx_learning_demo,
we use MCTX to build a simplified version of AlphaTensor-Quantum that can run on
a single machine (we strongly recommend access to a GPU to speed up the code).
Despite its simplicity, our demo is able to reproduce the following results of
the AlphaTensor-Quantum paper:
- Best reported T-count for three benchmark targets (Mod 5_4, Barenco Toff 3,
  and NC Toff 3) when running without gadgets (`use_gadgets=False`). This takes
  about 7800 iterations of the training loop on a Nvidia Quadro P1000 GPU.
- Best reported T-count for one benchmark target (Mod 5_4) when running with
  gadgets (`use_gadgets=True`). This takes about 450 iterations on the same GPU.

Our demo is intended to be a starting point for practitioners and researchers to
build on; it is by no means a complete implementation able to reproduce all the
results reported in the AlphaTensor-Quantum paper.

See the repository `README.md` for instructions on how to run the demo.
"""

import sys
import time

from absl import app
from absl import flags
import jax
import jax.numpy as jnp
import numpy as np

from alphatensor_quantum.src.demo import agent as agent_lib
from alphatensor_quantum.src.demo import checkpoints
from alphatensor_quantum.src.demo import demo_config

FLAGS = flags.FLAGS

flags.DEFINE_bool(
    'use_gadgets',
    True,
    'Whether to enable gadget reward accounting.',
)
flags.DEFINE_enum(
    'target_set',
    'default',
    ['default', 'original', 'mod5', 'barenco3', 'nc3'],
    'Named target set for the demo.',
)
flags.DEFINE_string(
    'target_manifest',
    None,
    'Optional imported-target manifest generated by tools/import_qasm_targets.py.',
)
flags.DEFINE_enum(
    'search_policy',
    'muzero',
    ['muzero', 'gumbel'],
    'MCTX policy-improvement operator.',
)
flags.DEFINE_integer(
    'gumbel_max_num_considered_actions',
    16,
    'Maximum number of root actions expanded by Gumbel MuZero.',
)
flags.DEFINE_float(
    'gumbel_scale',
    1.0,
    'Scale of root Gumbel noise for Gumbel MuZero.',
)
flags.DEFINE_enum(
    'algebraic_prior_mode',
    'none',
    ['none', 'delta', 'density', 'hybrid'],
    'Root-only algebraic action prior added to Gumbel policy logits.',
)
flags.DEFINE_float(
    'algebraic_prior_beta',
    0.0,
    'Scale of the algebraic action prior logits.',
)
flags.DEFINE_integer('seed', 2024, 'Random seed.')
flags.DEFINE_integer('batch_size', 0, 'Override batch size if positive.')
flags.DEFINE_integer(
    'num_mcts_simulations', 0, 'Override number of MCTS simulations if positive.'
)
flags.DEFINE_integer(
    'num_training_steps', 0, 'Override number of training steps if positive.'
)
flags.DEFINE_integer(
    'eval_frequency_steps', 0, 'Override eval frequency if positive.'
)
flags.DEFINE_integer(
    'max_num_moves', 0, 'Override maximum episode length if positive.'
)
flags.DEFINE_integer(
    'replay_capacity',
    0,
    'Replay buffer capacity. If 0, uses the original online loop.',
)
flags.DEFINE_integer(
    'replay_min_size',
    0,
    'Minimum valid replay entries before learner updates. If 0, uses '
    'train_batch_size.',
)
flags.DEFINE_integer(
    'train_batch_size',
    0,
    'Replay learner minibatch size. If 0, uses batch_size.',
)
flags.DEFINE_integer(
    'num_learner_steps_per_actor',
    1,
    'Number of replay learner updates after each actor rollout.',
)
flags.DEFINE_integer(
    'actor_rollout_length',
    0,
    'Replay actor rollout length. If 0, uses max_num_moves.',
)
flags.DEFINE_enum(
    'value_target_mode',
    'bootstrap',
    ['bootstrap', 'mc_return'],
    'Value targets for actor data.',
)
flags.DEFINE_integer(
    'num_value_quantiles',
    0,
    'Number of quantile outputs in the value head. If 0, uses scalar value.',
)
flags.DEFINE_float(
    'value_risk_quantile',
    0.0,
    'Lower quantile threshold used when reducing quantile values for search.',
)
flags.DEFINE_enum(
    'value_scalar_loss',
    'mse',
    ['mse', 'huber'],
    'Loss used by the scalar value head.',
)
flags.DEFINE_float(
    'value_huber_delta',
    1.0,
    'Delta parameter for scalar Huber value loss.',
)
flags.DEFINE_integer(
    'num_value_categorical_bins',
    0,
    'Number of categorical value bins. If 0, disables categorical value.',
)
flags.DEFINE_float(
    'value_support_min',
    None,
    'Minimum categorical value support. If omitted with categorical value, '
    'uses -2 * max_num_moves.',
)
flags.DEFINE_float(
    'value_support_max',
    None,
    'Maximum categorical value support. If omitted with categorical value, '
    'uses 0.',
)
flags.DEFINE_enum(
    'value_target_transform',
    'none',
    ['none', 'symlog'],
    'Invertible transform applied to the scalar value target before the '
    'value loss. `symlog` tames heavy-tailed returns (scalar value head only); '
    'the inverse is applied when the value is read back for search.',
)
flags.DEFINE_integer(
    'num_layers_torso',
    4,
    'Number of axial-attention torso layers.',
)
flags.DEFINE_integer(
    'num_heads',
    8,
    'Number of attention heads in each torso layer.',
)
flags.DEFINE_integer(
    'head_depth',
    8,
    'Depth of each attention head in the torso.',
)
flags.DEFINE_integer(
    'mlp_widening_factor',
    2,
    'MLP widening factor inside torso attention blocks.',
)
flags.DEFINE_string(
    'checkpoint_dir',
    None,
    'Optional directory for saving demo checkpoints.',
)
flags.DEFINE_integer(
    'checkpoint_frequency_steps',
    0,
    'Checkpoint frequency in steps. If 0, only the final step is saved.',
)
flags.DEFINE_string(
    'resume_checkpoint',
    None,
    'Optional checkpoint path to resume. The checkpoint config is reused.',
)
flags.DEFINE_enum(
    'checkpoint_payload',
    'full',
    ['full', 'eval'],
    'Payload to save in checkpoints. `eval` keeps only network params.',
)


def _target_name(target) -> str:
  return target.name.lower()


def _target_tag(config: demo_config.DemoConfig) -> str:
  names = [_target_name(target)
           for target in config.env_config.target_circuit_types]
  if len(names) == 1:
    return names[0]
  return f'multi{len(names)}'


def _should_save_checkpoint(current_step: int, total_steps: int) -> bool:
  if FLAGS.checkpoint_dir is None:
    return False
  if current_step >= total_steps:
    return True
  frequency = FLAGS.checkpoint_frequency_steps
  return frequency > 0 and current_step % frequency == 0


def main(_):
  # Set up the hyperparameters for the demo.
  checkpoint_payload = None
  if FLAGS.resume_checkpoint is None:
    run_seed = FLAGS.seed
    config = demo_config.get_demo_config(
        use_gadgets=FLAGS.use_gadgets,
        target_set=FLAGS.target_set,
        target_manifest=FLAGS.target_manifest,
        search_policy=FLAGS.search_policy,
        gumbel_max_num_considered_actions=(
            FLAGS.gumbel_max_num_considered_actions
        ),
        gumbel_scale=FLAGS.gumbel_scale,
        algebraic_prior_mode=FLAGS.algebraic_prior_mode,
        algebraic_prior_beta=FLAGS.algebraic_prior_beta,
        batch_size=None if FLAGS.batch_size <= 0 else FLAGS.batch_size,
        num_mcts_simulations=(
            None if FLAGS.num_mcts_simulations <= 0
            else FLAGS.num_mcts_simulations
        ),
        num_training_steps=(
            None if FLAGS.num_training_steps <= 0 else FLAGS.num_training_steps
        ),
        eval_frequency_steps=(
            None if FLAGS.eval_frequency_steps <= 0
            else FLAGS.eval_frequency_steps
        ),
        max_num_moves=None if FLAGS.max_num_moves <= 0 else FLAGS.max_num_moves,
        replay_capacity=FLAGS.replay_capacity,
        replay_min_size=(
            None if FLAGS.replay_min_size <= 0 else FLAGS.replay_min_size
        ),
        train_batch_size=(
            None if FLAGS.train_batch_size <= 0 else FLAGS.train_batch_size
        ),
        num_learner_steps_per_actor=FLAGS.num_learner_steps_per_actor,
        actor_rollout_length=(
            None if FLAGS.actor_rollout_length <= 0
            else FLAGS.actor_rollout_length
        ),
        value_target_mode=FLAGS.value_target_mode,
        num_value_quantiles=FLAGS.num_value_quantiles,
        value_risk_quantile=FLAGS.value_risk_quantile,
        value_scalar_loss=FLAGS.value_scalar_loss,
        value_huber_delta=FLAGS.value_huber_delta,
        num_value_categorical_bins=FLAGS.num_value_categorical_bins,
        value_support_min=FLAGS.value_support_min,
        value_support_max=FLAGS.value_support_max,
        value_target_transform=FLAGS.value_target_transform,
        num_layers_torso=FLAGS.num_layers_torso,
        num_heads=FLAGS.num_heads,
        head_depth=FLAGS.head_depth,
        mlp_widening_factor=FLAGS.mlp_widening_factor,
    )
    start_step = 0
  else:
    checkpoint_payload = checkpoints.load_checkpoint(FLAGS.resume_checkpoint)
    if checkpoint_payload['metadata'].get('checkpoint_payload', 'full') != 'full':
      raise ValueError('Only full checkpoints can be resumed.')
    config = checkpoint_payload['config']
    start_step = int(checkpoint_payload['metadata']['step'])
    run_seed = int(checkpoint_payload['metadata']['seed'])
  exp_config = config.exp_config

  # Initialize the agent and the run state.
  agent = agent_lib.Agent(config)
  if checkpoint_payload is None:
    run_state = agent.init_run_state(jax.random.PRNGKey(run_seed))
  else:
    # Initialize the environment frame before restoring the saved run state.
    agent.init_run_state(jax.random.PRNGKey(run_seed))
    run_state = checkpoint_payload['run_state']

  # Main loop.
  for step in range(
      start_step, exp_config.num_training_steps, exp_config.eval_frequency_steps
  ):
    time_start = time.time()
    run_state = agent.run_agent_env_interaction(step, run_state)
    current_step = step + exp_config.eval_frequency_steps
    time_taken = (time.time() - time_start) / exp_config.eval_frequency_steps
    # Keep track of the average return (for reporting purposes). We use a
    # debiased version of `avg_return` that only includes batch elements with at
    # least one completed episode.
    num_games = run_state.game_stats.num_games
    avg_return = run_state.game_stats.avg_return
    avg_return = jnp.sum(
        jnp.where(
            num_games > 0,
            avg_return / (1.0 - exp_config.avg_return_smoothing ** num_games),
            0.0
        ),
        axis=0
    ) / jnp.sum(num_games > 0, axis=0)
    print(
        f'Step: {current_step} .. '
        f'Running Average Returns: {avg_return} .. '
        f'Time taken: {time_taken} seconds/step'
    )
    for t, target_circuit in enumerate(config.env_config.target_circuit_types):
      tcount_value = float(-run_state.game_stats.best_return[t])
      tcount = int(tcount_value) if np.isfinite(tcount_value) else 'inf'
      print(f'  Best T-count for {_target_name(target_circuit)}: {tcount}')
    if _should_save_checkpoint(current_step, exp_config.num_training_steps):
      checkpoint_path = checkpoints.checkpoint_path(
          FLAGS.checkpoint_dir,
          target_tag=_target_tag(config),
          seed=run_seed,
          step=current_step,
      )
      checkpoints.save_checkpoint(
          checkpoint_path,
          run_state=run_state,
          config=config,
          step=current_step,
          seed=run_seed,
          command=list(sys.argv),
          change_of_basis_frame=agent.change_of_basis,
          checkpoint_payload=FLAGS.checkpoint_payload,
          extra_metadata={
              'target_tag': _target_tag(config),
              'targets': [
                  _target_name(target)
                  for target in config.env_config.target_circuit_types
              ],
          },
      )
      print(f'  Saved checkpoint: {checkpoint_path}')


if __name__ == '__main__':
  app.run(main)
